"""serialize audit hash chains

Revision ID: 2f10f322cd83
Revises: 96992c73e856
Create Date: 2026-07-10 08:02:54.365726
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2f10f322cd83'
down_revision: Union[str, None] = '96992c73e856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_heads',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    with op.batch_alter_table('audit_events') as batch_op:
        batch_op.add_column(sa.Column('chain_position', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_audit_org_position', ['organization_id', 'chain_position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events') as batch_op:
        batch_op.drop_constraint('uq_audit_org_position', type_='unique')
        batch_op.drop_column('chain_position')
    op.drop_table('audit_heads')
    # ### end Alembic commands ###
